security:
  jwt:
    secret-key: 45290e0801c91ddf3bbd5e6faac5c873fcabaa8bd8f1abd5219534d6dc91fa1c
    expiration-time: 1800000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    verify:
      host: http://localhost:${server.port}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080
